# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  particleSystem_config = debug

else ifeq ($(config),release)
  particleSystem_config = release

else ifeq ($(config),test)
  particleSystem_config = test

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := particleSystem

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

particleSystem:
ifneq (,$(particleSystem_config))
	@echo "==== Building particleSystem ($(particleSystem_config)) ===="
	@${MAKE} --no-print-directory -C . -f particleSystem.make config=$(particleSystem_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f particleSystem.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  test"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   particleSystem"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"